### ISSUE TITLE
Using hashing to generate probe and event ids

### ISSUE THREAD

**Issue by pittma** [auxoncorp/modality-probe#150]
## Problem

Using offsets is painful as a usage pattern to try to make sure that probe & event IDs are unique. Additionally, the new "component" design depends on globally unique probe IDs, and so making attempts to ensure that with minimal user intervention in the common case is desirable.

## Considerations

We've previously made attempts to keep the symbol <-> ID mappings "stable", which means that they don't necessarily change every single time you run the code scanner. If you were to run the code scanner twice on the same source tree without any changes to your instrumentation call-sites, then the same IDs should be generated as were before. We believe we can still maintain this behavior, while also making probe/event IDs less likely to collide.

We can still provide the escape hatch of manually managing ID ranges should a user desire to do so.

## Proposal

The existing code scanner tools maintain their own heuristics for whether or not a call-site has "changed" enough to warrant issuing a new ID or notifying the user as to a potential bugaboo with reusing, duplicating, moving, etc. their call-sites around. We can leverage this behavior combined with hash-based id generation to get sparser allocation of IDs while maintaining their existing stability.

## Challenges

Hash output can't be the entire space of a `u32` because we reserve part of the range of IDs for ourselves, so we have to truncate and/or offset hash results to fit inside `TOTAL_SPACE - RESERVED_RANGE`. Just feeding the probe/event symbol names to the hash function doesn't do enough to avoid collisions in the event that two people happened to name something the same thing (e.g. `LOG_MESSAGE` event or something that might have a probable conflict) due to human inclination "inventing" the same thing in parallel in different contexts.

To resolve this issue we can consider using the scanner tools' knowledge of deciding when something has "changed" to be a trigger to generate something like a transient UUID and feed that UUID to the hash function. This improves the probability that we have collisions in the hash space based on statistical distribution rather than similarities in how humans name things. 
However, while leveraging the tools' "changed enough" heuristics and only doing this transient UUID -> hash -> ID keeps the probe/event IDs stable in the ways we care about, there is still the possibility for collision in two different contexts.

1. The first is at code scanning time, where different UUIDs hash to the same value, and the proposal for resolving this is, just generate another UUID and hash it, rinse repeat until no collision. The down side to this naive approach is that as the hash space fills up we'll probably do this a lot, which could be slow, but we'll be able to tell when we're having that problem, so we can resolve it in a future where we're dealing with systems that have ~2 Billion probes and/or ~2 Billion discrete event definitions.

1. Secondarily, we can have collisions on the probe IDs at integration time when multiple components are being brought together, and the proposal for resolving this is to allow the end-user to opt into defining ID ranges at the time they invoke the scanning tools to provide bounds for the ID range that can be output. The methodology that's used to constrain the `u32` hash space to be `TOTAL_SPACE - RESERVED_RANGE` can probably be applied somewhat similarly here to make sure the hash output stays within some supplied bounds.

**Comment by mullr** [comment]
Why would we do this for event ids? There is a fully descriptive manifest for each component, so we don't presently have a collision problem there at all. We already have tooling to automatically mange the IDs there. It seems like this just introduces a collision problem where before we had none.

**Comment by nathanaschbacher** [comment]
We could do it only for probe IDs.

The reasons considered for event IDs were to have "the way" we do this be
the same in places where we have this kind of symbol to generated ID
problem. Also, because it increases the threshold of assumed potential
global uniqueness of looking at just and only an event ID rather than the
absolute certitude that any given system will definitely have the low end
of the event ID range used over and over again, but for different events.

Perhaps if doesn't matter? The consolidation of approaches along side the
modicum of increase in uniqueness expectation seemed like an okay trade-off
for the possibility of local compile-time collisions given the strategy is
pretty simple for getting around it and the possibility of collision is
already very, very low given the number of defined events in any given
component and the actual size of the available ID hash space.

**Comment by mullr** [comment]
> assumed potential global uniqueness of looking at just and only an event ID

I this is well understood, but just to clarify: event ids are defined to be unique at the component level /only/. They have no meaning until they are qualified by a probe or component id. Because we have no guarantee of uniqueness beyond this scope, we can't do anything useful with the fact the possibility that they're mostly unique. 

I believe that making them appear unique is in fact worse, in that it may mislead someone who is only looking at the data into believing they are globally unique and treating them as such. The current serial number scheme is very transparent at the data level and does not misrepresent the new scoping rules.

**Comment by nathanaschbacher** [comment]
That's true if they're entirely out of context that one can't qualify their
uniqueness if there were overlaps outside of the scope of a component.
However, if you have a bunch of components and you see that there are no
colliding event IDs then you do get to trivially consider them as unique
_for that system_, and checking that there are no collisions is a pretty
simple to to determine to provide that extra bit of allowable assumption
when possible. Whereas it's entirely precluded from doing this when
definitely the event IDs will be reused as a matter of standard operating
procedure.

I don't have particularly strong feelings about it one way or the other
because really nothing is meaningfully impacted right now by either method.

If we don't do it, then we _always_ have to consider an event ID's discrete
uniqueness fully qualified by component. If we do do this, then there are
some scenarios (a statistically significant number of them for any well
behaved hash function) that we can check trivially at SUT integration where
events could be considered globally unique.
